<?php 
   include('model/event.php');
   include('model/historicalSites.php');
   include('model/groupLocation.php');
   include('model/serviceType.php');
   include('model/image360.php');
   include('model/advertisement.php');
   include('model/restaurant.php');
 ?>